### PR TITLE
Implement `wp db check`

### LINKED ISSUE #3273: wp db check
We have optimize and repair but no check.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #3273

### CODE REVIEW

**Comment by szepeviktor** [comment]
> `mysqlcheck` apparently doesn't output when STDOUT is piped

You could try `mysqlcheck | cat`.

The cause could be that Travis is not running on a terminal...

**Comment by szepeviktor** [comment]
> The cause could be that Travis is not running on a terminal...

No, it fails on my terminal also.

**Comment by danielbachhuber** [comment]
> No, it fails on my terminal also.

This branch with my two most recent changesets fails on your terminal?

**Comment by szepeviktor** [comment]
My stdout is only 1 line during Behat.

I can't imagine how this does not reach stdout:
https://github.com/MariaDB/server/blob/10.1/client/mysqlcheck.c#L1036

**Comment by szepeviktor** [comment]
I replaces `$final_cmd` in utils.php with dumper.sh
```bash
#!/bin/bash

echo "This is STDOUT" >&1
echo "This is STDERR" >&2
```
It works OK.

**Comment by szepeviktor** [comment]
The word is: **empty**

**Pull request merged**
