### PR TITLE
Experimental RPM packaging

### PR DESCRIPTION
**Pull request by szepeviktor**
1. Download the binary
1. Replace version placeholder in spec file
1. Create man page
1. Build the package
1. Run linter

I am not sure it is very rpm-ish.

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber Could we get a small *audience* to install our RPM?

**Comment by danielbachhuber** [comment]
> Could we get a small audience to install our RPM and send us some feedback?

Yes, I can do that. Give me a little bit of time.

**Comment by szepeviktor** [comment]
Thank you.
Of course the script in this PR generates the package.

**Comment by danielbachhuber** [comment]
Landing this so I can work on integrating it in https://github.com/wp-cli/rpm-build

**Comment by szepeviktor** [comment]
Thanks.

**Pull request merged**
