### PR TITLE
Fix parsing of arguments for `WP_CLI::runcommand()` with `launch=false`

### LINKED ISSUE #4741: Quotes in arguments get stripped when using WP-CLI::runcommand with 'launch'=>false
Quotes in arguments get stripped when using WP-CLI::runcommand with `'launch'=>false` set

### Steps to reproduce:

1. Create a file, `test.php`, containing the following:

```
<?php
WP_CLI::runcommand( 'post create --post_title="Hello world!"', ['launch' => false]);
```

2. Run `wp eval-file test.php`

### Expected result:

A post is created with the title 'Hello world!"

### Actual result

```
$ wp eval-file test.php
Error: Unable to read content from 'world!"'.
```

### Other info

This doesn't seem to happen if `'launch'=>true`

### PR DESCRIPTION
**Pull request by schlessera**
I added unit tests for the broken cases and modified the regular expression so that it correctly parses these cases as well.

Fixes #4741

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera Were the first two builds supposed to fail?

**Comment by schlessera** [comment]
@danielbachhuber Not sure what you mean. All commits were meant to pass and did pass, but the second one added edge cases the first one didn't test against.
Third one is just a simplification.

**Comment by schlessera** [comment]
Oh, and the tests do fail with the original regex.

**Comment by danielbachhuber** [comment]
> All commits were meant to pass and did pass, but the second one added edge cases the first one didn't test against.

Ok, cool. I've run into an issue before where Travis passed but I expected it to fail. Wanted to make sure it wasn't the case here.

**Pull request merged**
