### PR TITLE
update `wp cli info`

### PR DESCRIPTION
**Pull request by thrijith**
to update #4599 
change output format to table : https://github.com/wp-cli/wp-cli/pull/4604#discussion_r161050368

not sure if this is what you expected @gitlost, please provide your inputs for any changes.

### CODE REVIEW

**Comment by schlessera** [comment]
I wonder if people use the output from `wp cli info` for scripting purposes. If so, the above is a breaking change. I'll ask in #cli to get some (limited) feedback.

**Comment by gitlost** [comment]
Yes, apologies for the misleading comment @thrijith, although the output does look a lot better (though could do without the header). Please note this isn't a high priority at the moment so won't be reviewed immediately and may not make 1.5.0.

**Comment by thrijith** [comment]
ok @schlessera

**Comment by thrijith** [comment]
no problem @gitlost  will remove the header.

**Comment by gitlost** [comment]
> will remove the header.

@thrijith if instead you have time to investigate https://github.com/wp-cli/scaffold-command/issues/109 and whether the output is compliant in other cases apart from the taxonomy one you fixed that would very much be appreciated!

**Comment by thrijith** [comment]
ok @gitlost will work on it then

**Comment by gitlost** [comment]
@thrijith am going to leave this PR out of 1.5.0 but will revisit shortly afterwards, ta!

**Comment by gitlost** [comment]
@thrijith re headerless table, at the moment need to workaround limitations of `Utils\format_items()`, `WP_CLI\Formatter` and `cli\Table` so maybe do
```
			$table = new \cli\Table;
			$table->setRows( $info );
			$table->setRenderer( new \cli\table\Ascii );
			$lines = array_slice( $table->getDisplayLines(), 2 ); // Remove header and border.
			foreach ( $lines as $line ) {
				\WP_CLI::line( $line );
			}
```

**Pull request merged**
