### PR TITLE
Implement #1011

### PR DESCRIPTION
**Pull request by nyordanov**
I'm looking for comments on the general idea behind this. I'll add tests later.

Here is how it works:
1. Unless we already know that an update is available, run `wp cli check-update` on shutdown with 1/50 probability. It is a separate, non-blocking, process.
2. If `wp cli check-update` finds any updates, it will touch `~/.wp-cli/has-new-version`.
3. `wp help` will display an error message if `~/.wp-cli/has-new-version` exists, but only after exiting from the pager.
4. `wp cli update` will unlink `~/.wp-cli/has-new-version` if it exists.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> I'm looking for comments on the general idea behind this.

Interesting approach. It's a bit different than I would go about it, but I don't know if I have strong opinions yet.

Here's how I was thinking about it:

* Only perform the check if `wp` or `wp help *` was run, to ensure we only produced unexpected output when an interactive session was taking place.
* Write a `next-check-time` file to the cache directory with the time after which the next check should take place. If the file is writable, then it's safe to make the check at the appropriate allotted time. If the file isn't writable, or WP-CLI itself isn't writable, then bail on ever making checks, to prevent the update check from happening on every execution.
* If there's an update check available, block the current execution of `wp` or `wp help` and indicate which version is available (and which version the user currently has), and perform the update if `y` is provided at the prompt.

Running the update check on shutdown is a neat idea, although I don't know if it offers any key advantages.

This project might also be a bit of an opportunity to produce a lightweight API for commands to store data to the filesystem.

**Comment by nyordanov** [comment]
> Running the update check on shutdown is a neat idea, although I don't know if it offers any key advantages.

The main advantage is that the check is non-blocking. Also, if there is a way to reliably detect an interactive session we will be able to show the "update available" message immediately.

Storing the next check time is a good idea, see https://github.com/nyordanov/wp-cli/commit/148c4098d0537af85e9a62876643652b8ec9b421.

> block the current execution of `wp` or `wp help` and indicate which version is available (and which version the user currently has), and perform the update if y is provided at the prompt.

Something like https://github.com/nyordanov/wp-cli/commit/6f308217cd7ee0cf4aacf9e6eb4176338f263b3f? This is not ideal, though - `help` will perform an additional `cli check-update` and block, which might make it unusable if you can't reach Github. Perhaps we can do `cli check-update` in the background, so that by the time the user exits the pager, we would have already fetched the list of updates?

**Comment by danielbachhuber** [comment]
> Perhaps we can do cli check-update in the background, so that by the time the user exits the pager, we would have already fetched the list of updates?

Dig it. We should make sure it's not a persistent nag though. If they've chosen to skip it, it will remain skipped until the next version.

**Comment by danielbachhuber** [comment]
@nyordanov any ideas why your builds are taking 50 min to run?

**Comment by danielbachhuber** [comment]
@nyordanov planning to pick things up again soon?

**Comment by danielbachhuber** [comment]
Closing in favor of #2538

**Pull request closed without merging**
