### PR TITLE
Only skip `@github-api` tests when `GITHUB_TOKEN` isn't present

### PR DESCRIPTION
**Pull request by danielbachhuber**
From https://github.com/wp-cli/package-command/pull/47

### CODE REVIEW

**Comment by gitlost** [comment]
The PHP 5.3 issue is to do with it not having a `PHP_BINARY` define I think, so `WP_CLI::get_php_binary()` needs to be updated to fall back to `PHP_BINDIR` as well - will push a fix for it...

**Comment by danielbachhuber** [comment]
@gitlost Cool, thanks

**Comment by gitlost** [comment]
Oh just noticed that `FeatureContext` has its own version of `get_php_binary()` - that should probably be updated as well...

**Comment by gitlost** [comment]
Ha and also be made static...

**Pull request merged**
