### PR TITLE
DB Operations tests

### PR DESCRIPTION
**Pull request by szepeviktor**
We were playing with an empty database.

Complements #3332

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> We were playing with an empty database.

Fancy that. Good catch :)

**Comment by szepeviktor** [comment]
Could you restore the whole table list in db.feature?

**Comment by danielbachhuber** [comment]
> Could you restore the whole table list in db.feature?

I've created a new `db-check.feature`, which is why the tests passed for me. Given all of the tables don't exist in 3.7, I think it's fine to only check one table.

**Comment by szepeviktor** [comment]
Thanks.

**Pull request merged**
