### PR TITLE
make-phar: strip autoloads of phpcs stuff.

### PR DESCRIPTION
**Pull request by gitlost**
Related https://github.com/wp-cli/package-command/issues/44

Strips the phpcs entries "dealerdirect/phpcodesniffer-composer-installer", "wp-coding-standards/wpcs" (squizlabs), and "wimg/php-compatibility" (added in https://github.com/wp-cli/wp-cli/pull/4339 and https://github.com/wp-cli/wp-cli/pull/4402) from the `autoload*`s in `utils/make-phar.php`.

Only partly addresses https://github.com/wp-cli/package-command/issues/44 in that that issue needs further investigation.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@gitlost This seems to have fixed https://github.com/wp-cli/package-command/issues/44 for me. Is that not the case for you?

**Comment by gitlost** [comment]
I couldn't reproduce it locally https://github.com/wp-cli/package-command/issues/44#issuecomment-340524161, except by doing
```bash
composer global require -dev dealerdirect/phpcodesniffer-composer-installer
```
which was why I was hesitant. Is/was there a global require in your `~/.composer/composer.json`?

**Comment by danielbachhuber** [comment]
> Is/was there a global require in your `~/.composer/composer.json`?

Nope. Here's the reproduction steps from one of my webservers:

```
web590.webfaction.com ➜  ~  wp cli update --stable --yes
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar...
md5 hash verified: 179fc8dacbfe3ebc2d00ba57a333c982
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest stable release.
web590.webfaction.com ➜  ~  alias wp="php70 -d memory_limit=512M $HOME/bin/wp"
web590.webfaction.com ➜  ~  wp package list

Warning: include(phar:///home/handbuiltco/bin/wp/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php): failed to open stream: phar error: "vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php" is not a file in phar "/home/handbuiltco/bin/wp" in phar:///home/handbuiltco/bin/wp/vendor/composer/ClassLoader.php on line 444

Warning: include(): Failed opening 'phar:///home/handbuiltco/bin/wp/vendor/dealerdirect/phpcodesniffer-composer-installer/src/Plugin.php' for inclusion (include_path='phar:///home/handbuiltco/bin/wp/vendor/phpunit/php-token-stream:phar:///home/handbuiltco/bin/wp/vendor/phpunit/phpunit-mock-objects:phar:///home/handbuiltco/bin/wp/vendor/phpunit/php-code-coverage:phar:///home/handbuiltco/bin/wp/vendor/phpunit/phpunit:phar:///home/handbuiltco/bin/wp/vendor/symfony/yaml:.:/usr/local/share/pear70') in phar:///home/handbuiltco/bin/wp/vendor/composer/ClassLoader.php on line 444
+------------------------------------+------------------+------------+--------+----------------+
| name                               | authors          | version    | update | update_version |
+------------------------------------+------------------+------------+--------+----------------+
| danielbachhuber/php-compat-command |                  | dev-master | none   |                |
| wp-cli/dist-archive-command        | Daniel Bachhuber | dev-master | none   |                |
| wp-cli/find-command                |                  | dev-master | none   |                |
| wp-cli/scaffold-package-command    | Daniel Bachhuber | dev-master | none   |                |
+------------------------------------+------------------+------------+--------+----------------+
web590.webfaction.com ➜  ~  wp cli update --nightly --yes
Downloading from https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar...
md5 hash verified: 4409ec14f8c5e729738eef5efa10dd92
New version works. Proceeding to replace.
Success: Updated WP-CLI to the latest nightly release.
web590.webfaction.com ➜  ~  wp package list
+------------------------------------+------------------+------------+--------+----------------+
| name                               | authors          | version    | update | update_version |
+------------------------------------+------------------+------------+--------+----------------+
| danielbachhuber/php-compat-command |                  | dev-master | none   |                |
| wp-cli/dist-archive-command        | Daniel Bachhuber | dev-master | none   |                |
| wp-cli/find-command                |                  | dev-master | none   |                |
| wp-cli/scaffold-package-command    | Daniel Bachhuber | dev-master | none   |                |
+------------------------------------+------------------+------------+--------+----------------+
```
So, it seems to be fixed now in the nightly build.

**Comment by schlessera** [comment]
I can confirm, the issue is fixed for me as well on nightly.

**Comment by gitlost** [comment]
Okay, I'm just puzzled what's triggering the lookup. It'd be nice to nail it.

**Comment by danielbachhuber** [comment]
@gitlost `Dealerdirect\Composer\Plugin` is a Composer plugin, no? Wouldn't this mean it's always loaded when Composer is loaded?

**Comment by gitlost** [comment]
Okay it must be in your `~/.wp-cli/packages/vendor/composer/installed.json` for some reason (as it's not in `~/.composer/composer.json` and wouldn't be in `~/.wp-cli/packages/composer.json`) - I think.

(A topical little twist in light of https://github.com/wp-cli/package-command/issues/43 is that the git hub user is the mixed-case `DealerDirect`...)

**Pull request merged**
