### PR TITLE
Export and list tables with prefix

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @szepeviktor. Can you include some tests?

**Comment by szepeviktor** [comment]
And the [search](https://github.com/wp-cli/wp-cli/issues/1225#issuecomment-49925012) feature.

**Comment by szepeviktor** [comment]
@danielbachhuber Please help me out with a decision:
How should [`get_table_list`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/search-replace.php#L137-L150) and [`tables`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/db.php#L202-L215) be merged?

**Comment by danielbachhuber** [comment]
@szepeviktor I think I'd like us to continue with #1801, as it provides more flexibility.

**Comment by szepeviktor** [comment]
@danielbachhuber Please remember that this is `db export` and #1801 is s&r.

**Comment by danielbachhuber** [comment]
> Please remember that this is db export

Oh, right :smile: Can we follow the same pattern then?

**Comment by szepeviktor** [comment]
This is why I was asking:

How should s&r/[`get_table_list`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/search-replace.php#L137-L150) and db/[`tables`](https://github.com/wp-cli/wp-cli/blob/master/php/commands/db.php#L202-L215) be merged?

**Comment by danielbachhuber** [comment]
> How should s&r/get_table_list and db/tables be merged?

Oh, I see. Let's abstract to `php/utils-wp.php` ?

**Comment by danielbachhuber** [comment]
Closing in favor of #2250

**Pull request closed without merging**
