### PR TITLE
Add command for managing maintenance mode

### PR DESCRIPTION
**Pull request by thrijith**
Fixes https://github.com/wp-cli/ideas/issues/114

### CODE REVIEW

**Comment by schlessera** [comment]
Marked the related issue as being `state:approved`.

**Comment by schlessera** [comment]
@thrijith I started playing around with this and testing it. Before I add pull request comments, though, I think we should first put it into the correct place, as it shouldn't be a part of the framework itself.

I'll create a new repository `wp-cli/maintenance-mode`.

I think the syntax should be:
`wp maintenance-mode activate`
`wp maintenance-mode deactivate`
`wp maintenance-mode status` (returns human-readable output)
`wp maintenance-mode is-active` (returns exit code for easy scripting)

**Comment by schlessera** [comment]
Here's the repository: https://github.com/wp-cli/maintenance-mode-command

**Comment by thrijith** [comment]
>I think we should first put it into the correct place, as it shouldn't be a part of the framework itself.

@schlessera Done.

Closing in favour of https://github.com/wp-cli/maintenance-mode-command/pull/1

**Pull request closed without merging**
