### PR TITLE
Feature/symfony 3 components

### PR DESCRIPTION
**Pull request by balintsera**
Experimental: Symfony 3 components

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Could you explain in greater detail your intent with this pull request?

**Comment by balintsera** [comment]
Hi,
sorry for the mess, my initial intention was to update wp-cli to symfony 3 because I wanted to install wp-cli via Composer along with WP inside of a Symfony 3 installation :) 
The problem is, wp-cli depends on different symfony packages. 

It’s just an experiment, but if you like the idea maybe it could find its way to some dev branch, so I can try it in the wp + symfony 3 env. 

I realized that there are hardcoded mysql creditentials in Behat, so I tried to replace it to an environment variable based solution but it breaks on travis (but not locally). I’m a bit confused about this, and have to create a pr every time I want to find out why travis fails. :( 

So please ignore these pr-s :)

Balint Sera

**Comment by danielbachhuber** [comment]
Ok. You should enable Travis on your fork so you aren't dependent on the upstream project's limited number of builds.

**Comment by balintsera** [comment]
ok, thank you, good idea, I'm on it

**Pull request closed without merging**
