### PR TITLE
Avoid wp_clean_update_cache() in WordPress versions before 4.1.0

### LINKED ISSUE #1849: Don't use `wp_clean_update_cache()` in WP 4.0 context
It was introduced in WP 4.1

From #1847

### PR DESCRIPTION
**Pull request by szepeviktor**
Fixes #1849
$ php -l CommandWithTranslation.php
No syntax errors detected in CommandWithTranslation.php

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber Could it be that the language cache does not regenerate itself?

**Comment by szepeviktor** [comment]
But that does not make `update` column to appear.

**Comment by danielbachhuber** [comment]
We probably need to replicate the function entirely as a private method.

**Comment by danielbachhuber** [comment]
> replicate the function entirely as a private method

By which I mean, put the logic for `wp_clean_update_cache()` into a private method, and use that instead. Sorry I wasn't more clear to start.

**Comment by szepeviktor** [comment]
I hope it gets green.

**Comment by szepeviktor** [comment]
@danielbachhuber This error is beyond my understanding.

**Comment by szepeviktor** [comment]
@danielbachhuber Please fix it. It might take 2 minutes for you.

**Comment by danielbachhuber** [comment]
> Please fix it. It might take 2 minutes for you.

Ok, I will do when I have some time.

**Comment by danielbachhuber** [comment]
Handling in #1875

**Comment by szepeviktor** [comment]
Thank you.

**Pull request closed without merging**
