### PR TITLE
Improve Composer change logs

### LINKED ISSUE #3877: Improve Composer update change logs
As we directly use the output of the Composer Update command in the commit messages, we should consider adding the package [pyrech/composer-changelogs](https://github.com/pyrech/composer-changelogs) to the development requirements, to make them more useful.

Demo

### PR DESCRIPTION
**Pull request by schlessera**
Add `pyrech/composer-changelogs` package to development dependencies to improve the generated change logs that can be pasted into update commit messages.

Note: This PR includes additional changes because Composer has changed the timestamp format for the lock file.

Fixes #3877

### CODE REVIEW

**Comment by schlessera** [comment]
`pyrech/composer-changelogs` is PHP 5.4+.

It seems that the only 5.4-specific feature that is being used is short array syntax. I'll submit a quick PR to see if the maintainer if willing to lower the requirement.

**Comment by schlessera** [comment]
Related PR: https://github.com/pyrech/composer-changelogs/pull/44

**Comment by danielbachhuber** [comment]
> It seems that the only 5.4-specific feature that is being used is short array syntax. I'll submit a quick PR to see if the maintainer if willing to lower the requirement.

👍

**Comment by danielbachhuber** [comment]
@schlessera I've created a WP-CLI org fork we can use: https://github.com/wp-cli/composer-changelogs

Can you update there?

**Pull request merged**
