### PR TITLE
Use warning instead of colorize to fix warning output

### PR DESCRIPTION
**Pull request by sagarnasit**
closes: #5288

### CODE REVIEW

**Comment by schlessera** [comment]
Thanks for the PR, @sagarnasit!

I just tested how the output actually looks as a warning.

Before:
Image 2019-10-08 at 6 59 49 AM
After:
Image 2019-10-08 at 6 58 51 AM

I think the change is considerably worse in terms of getting people's attention.

I'm now thinking that it might be preferable to stick with the previous coloring, but add a mechanism to send that one to STDERR instead...

**Comment by schlessera** [comment]
Using `WP_CLI::error_multi_line()` would work:
Image 2019-10-08 at 7 08 48 AM

@sagarnasit Can you change the code to use `WP_CLI::error_multi_line()` instead of `WP_CLI::warning()` ?

Note: That method requires an array of lines, instead of a string, as its input.

**Comment by schlessera** [comment]
Uhm, sorry, forget my last comment. This just seems too aggressive in daily usage. We'll have to add a new mechanism here to use the initial coloring, but with STDERR instead of STDOUT.

**Comment by sagarnasit** [comment]
@schlessera I'm not sure how to proceed next with a new mechanism. If you can give more details on that, that would be helpful.

**Comment by schlessera** [comment]
The required change will include a modification of the logger interface, so I need to think this through first. I'll try to come up with a precise plan of attack.

**Comment by schlessera** [comment]
I'm merging this as-is for now to make sure we don't continue sending the message to STDOUT.

The new "design" will need to wait for 2.5.0 then.

**Pull request merged**
