### PR TITLE
Add get home dir

### PR DESCRIPTION
**Pull request by Ippey**
Related #4091.
Add get_home_dir() function into Utils.

### CODE REVIEW

**Comment by gitlost** [comment]
Thanks @Ippey - could you have wp-cli use the new function - see `WP_CLI::get_cache()` (https://github.com/wp-cli/wp-cli/blob/master/php/class-wp-cli.php#L77) and also the 3 instances in `WP_CLI\Runner`?

Also to avoid test bleed it's nice if tests leave things as they find them so could you save/restore the environment in the test (see eg https://github.com/wp-cli/php-cli-tools/blob/master/tests/test-shell.php#L15). Also the test should also use the WP coding style. Ta!

**Comment by Ippey** [comment]
@gitlost Thank you for your checking! I'll try them tonight.

**Comment by danielbachhuber** [comment]
Looks good, thanks @Ippey !

**Comment by miya0001** [comment]
This PR was opened at contributor day at WordCamp Kyoto. 😄

**Pull request merged**
