### PR TITLE
PR for Need skip themes option #1594 

### PR DESCRIPTION
**Pull request by oneumyvakin**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
I think we could call this `--skip-theme` because only one theme can be loaded at any given time.

Can you add [functional tests](https://github.com/wp-cli/wp-cli/blob/master/CONTRIBUTING.md#functional-tests) too, please?

**Comment by scribu** [comment]
> I think we could call this --skip-theme because only one theme can be loaded at any given time.

Technically, if it's a child theme, there are two: the child and the parent.

**Comment by scribu** [comment]
NB: I'm not implying that being able to only skip the child or only skip the parent is actually useful.

**Comment by danielbachhuber** [comment]
> Technically, if it's a child theme, there are two: the child and the parent.

Er, but you don't ever activate two themes at once. Either the child theme is active, or the parent.

Technically, a theme can require whatever code it wants. WordPress only knows of one active theme.

**Comment by oneumyvakin** [comment]
As I remember there can be a list of themes in CLI: 
--skip-themes=t1,t2

or config: 
skip-themes:
- t1
- t2

In my case config is a global config for several independent WPs, so I can skip problem themes by name and do not skip all other themes.

**Comment by oneumyvakin** [comment]
Sorry guys, I've to create new PR #1599 
Tests are added.

**Comment by danielbachhuber** [comment]
> In my case config is a global config for several independent WPs, so I can skip problem themes by name and do not skip all other themes.

@oneumyvakin You've convinced me of the utility of `--skip-themes` instead of `--skip-theme`.

**Pull request closed without merging**
