### PR TITLE
Reduce included files (behat/phpunit in particular). Add 'cli' test build option.

### PR DESCRIPTION
**Pull request by gitlost**
Issue https://github.com/wp-cli/wp-cli/issues/4170

Does not include behat or phpunit files.

Tries in general to only include files needed - for instance only specific symfony components, and no spdx-licenses, command, console or Pear stuff for composer.

Excludes "composer/ca-bundle/res/cacert.pem" as it doesn't seem to be needed as "rmccue/requests/library/Requests/Transport/cacert.pem" is used instead.

Processes the autoload_* files to remove unused entries.

Also adds a `build` option to make a much reduced test phar that can only run `cli` commands such as `wp --version` and `wp cli check-update` - although not used here it will be in a future patch to speed up testing (`cli.feature` in particular). (See https://github.com/gitlost/wp-cli/pull/12 for the gory details.)

Also removes the "Include base project files, because the autoloader will load them" branch, added in https://github.com/wp-cli/wp-cli/pull/3923, that doesn't seem to be needed (I think).

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @gitlost. It'd be nice to get https://github.com/wp-cli/wp-cli/issues/4108 running completely before we land this.

**Comment by gitlost** [comment]
Yes, are there ideas floating around as to how to do that?!

**Comment by danielbachhuber** [comment]
> Yes, are there ideas floating around as to how to do that?!

@schlessera had it running, but I'm unsure of its current status.

**Comment by schlessera** [comment]
I'll try to move #4108 forward, it is one of the tasks I wanted to be done for 1.3.0 as well.

**Comment by danielbachhuber** [comment]
@gitlost Happy with this? If so, feel free to merge at your convenience.

I'd like to get this landed sooner rather than later so we can see if any bugs shake out of it.

**Pull request merged**
