### PR TITLE
Only skip replace when array is a reference to an existing array

### LINKED ISSUE #3656: Multiple substrings are not getting replaced while doing search-replace
Today, I tried to do a search and replace on an email. There were a total of 10 occurrences in wp database. One row in wp_options table alone had two occurrence of the old email. Only the first one got replaced during the first run of wp-cli. So only 9 occurrence in total got replaced. I had to run search-replace again in order to replace the second occurrence in that row in wp_options table.

### PR DESCRIPTION
**Pull request by danielbachhuber**
When two arrays contain the same value, we want both to be replaced.

Fixes #3656

### CODE REVIEW

**Comment by danielbachhuber** [comment]
For anyone that wants to try their hand at this, you'll want to `./vendor/bin/phpunit` locally and look at `SearchReplacer->_run()` to see where the problem is.

**Comment by miya0001** [comment]
I found that test fails in this line.

https://github.com/miya0001/wp-cli/blob/master/tests/test-search-replace.php#L36
https://travis-ci.org/miya0001/wp-cli/jobs/189074128

**Comment by miya0001** [comment]
I put `var_dump()` like following.
https://github.com/miya0001/wp-cli/blob/624b94dc905452bf59dff7bf8cbb7998306e0898/php/WP_CLI/SearchReplacer.php#L97-L102

Following is result in my local machine.
```
$ phpunit 
PHPUnit 5.6.2 by Sebastian Bergmann and contributors.

.................Debug: This is a test message. (0.001s)
...int(2)
................                              36 / 36 (100%)

Time: 88 ms, Memory: 10.00MB
```

But number hasn't displayed on Travis CI
https://travis-ci.org/miya0001/wp-cli/builds/189092231

There is an infinite loop. But I haven't cause of it now.

**Comment by miya0001** [comment]
Ah,
```
array(2) {
  'prop' =>
  string(3) "foo"
  'self' =>
  array(2) {
    'prop' =>
    string(3) "foo"
    'self' =>
    &array
  }
}
```

But on my local environment
```
array(2) {
  ["prop"]=>
  string(3) "foo"
  ["self"]=>
  &array(2) {
    ["prop"]=>
    string(3) "foo"
    ["self"]=>
    *RECURSION*
  }
}
```
There are not `*RECURSION*`...

**Comment by danielbachhuber** [comment]
> Ah, There are not `*RECURSION*` on Travis ...

Oh, interesting. I hope 813bbaef6108bba2cb54270e837701eab6e2c716 works then.

**Comment by miya0001** [comment]
Yes! It is really interesting. I am seeing documentation of the `php.ini`.

**Pull request merged**
