### PR TITLE
Experimental support for PHP 7

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #1842

### CODE REVIEW

**Comment by szepeviktor** [comment]
@danielbachhuber I think the only wp-cli error is
```
PHP Warning:  fwrite(): supplied resource is not a valid stream resource in phar:///tmp/wp-cli-phar/wp/php/WP_CLI/Loggers/Regular.php on line 24
```

**Comment by szepeviktor** [comment]
Could you fix it?

**Comment by danielbachhuber** [comment]
I can, but it likely won't be for at least a couple weeks.

**Comment by danielbachhuber** [comment]
@szepeviktor Can you do some searching to see what changed in PHP 7 that might cause the error? c24667a3bfc29ca766d6f02c3fec1d55d84ff1ff didn't have an effect, and I haven't found anything yet.

**Comment by centminmod** [comment]
FYI, PHP 7.0.0 Alpha1 is released and WP-CPI throws up a bunch of errors on installing some WP Plugins https://community.centminmod.com/posts/14892/

**Comment by szepeviktor** [comment]
The PHP7 ticket: https://core.trac.wordpress.org/ticket/31982

**Comment by szepeviktor** [comment]
Are you planning to add this one to the next release?

**Comment by danielbachhuber** [comment]
> Are you planning to add this one to the next release?

No, as no one has come up with a passing build yet.

**Comment by szepeviktor** [comment]
`PHP 7.1.0-dev (cli) (built: Sep 18 2015 19:10:01)` is out.
@danielbachhuber Could you run CI again? I hope they update their nightly.

**Comment by szepeviktor** [comment]
Which of these solves our problem???
https://bugs.php.net/search.php?limit=30&order_by=id&direction=DESC&cmd=display&status=Closed&bug_type=All&phpver=7.0

**Comment by danielbachhuber** [comment]
Taking a second attempt at this in #2072

**Pull request closed without merging**
