### PR TITLE
Implement `\Countable` for `\WP_CLI\Iterators\CSV`

### PR DESCRIPTION
**Pull request by danielbachhuber**
This makes it possible to start a progress bar for a CSV file:

```php
$iterator = new \WP_CLI\Iterators\CSV( $csv_file );
$progress = \WP_CLI\Utils\make_progress_bar( 'Processing list', count( $iterator ) );
```

The use of `SplFileObject` avoids reading the entire file to memory.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Not sure what the build failure is now...

**Comment by schlessera** [comment]
Seems to be signature changes due to refactoring in Core trunk. I'll take a look at fixing this.

**Comment by schlessera** [comment]
Tried to fix the build failure through #5283, let's see what Travis thinks of my approach.

**Comment by danielbachhuber** [comment]
> Using the `SplFileObject` makes total sense here for the count, but is there a valid reason for not just using it all the way?

To avoid an unnecessary refactor. I suspect it makes zero functional difference that two separate approaches are used.

**Comment by schlessera** [comment]
Can you pull latest `master` to get the build failure fix?

**Comment by danielbachhuber** [comment]
> Can you pull latest `master` to get the build failure fix?

Yep, done.

**Pull request merged**
