### PR TITLE
Use WP_CLI::line for new line

### PR DESCRIPTION
**Pull request by anhskohbo**
We need use line() at here.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> We need use line() at here.

Why? `WP_CLI::log()` supports the `--quiet` flag, while `WP_CLI::log()` does not.

**Comment by anhskohbo** [comment]
When you run `wp import wp.xml` without `--debug` flag.

**Comment by danielbachhuber** [comment]
> When you run `wp import wp.xml` without `--debug` flag.

Sorry, I'm not sure I follow. Can you elaborate?

**Comment by anhskohbo** [comment]
Sorry, I misunderstood idea. I think `WP_CLI::success( "Finished importing from '$file' file." );` will be display after a blank line.

Close pull request!

**Pull request closed without merging**
