### PR TITLE
Convert 'install' to 'installation'

### PR DESCRIPTION
**Pull request by KushibikiMashu**
For #4541 ("installation" instead of "install")

### CODE REVIEW

**Comment by swissspidy** [comment]
Thanks for the PR!

I just noticed that there are a few more instances of "WordPress install" instead of "WordPress installation" (e.g. `No WordPress install found`) in the following files:

* `features/config.feature`
* `features/help.feature` 
* `php/config-spec.php` 
* `php/WP_CLI/Runner.php` 

Wanna change these as well while you are at it? 🙂

**Comment by KushibikiMashu** [comment]
@swissspidy Thank you for your advise!
I'll check these files and give some commits during WordCamp Tokyo😄

**Comment by KushibikiMashu** [comment]
@swissspidy Hi!
I read Travis log and tried to modify the code to resolve the problem in failing.
I'll try to run behat test locally and examine the code in detail😅

**Comment by wojsmol** [comment]
@KushibikiMashu Please see https://github.com/KushibikiMashu/wp-cli/pull/2 for remaining tests fixes.

**Comment by schlessera** [comment]
Thanks for the pull request, @KushibikiMashu!

**Pull request merged**
