### PR TITLE
Permit `dev-master` for required WP-CLI packages

### PR DESCRIPTION
**Pull request by danielbachhuber**
Hopefully this fixes:

```
 Problem 1
    - Installation request for wp-cli/package-command dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1 -> satisfiable by wp-cli/package-command[dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1].
    - wp-cli/wp-cli dev-master requires wp-cli/package-command ^1.0 -> satisfiable by wp-cli/package-command[v1.0.0].
    - Can only install one of: wp-cli/package-command[v1.0.0, dev-2a4ac19b859ac77c92e60efc972e539c6b834fb1].
    - Installation request for wp-cli/wp-cli dev-master -> satisfiable by wp-cli/wp-cli[dev-master].
```

From https://travis-ci.org/wp-cli/package-command/jobs/213828196
Related https://github.com/wp-cli/package-command/pull/2

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera Does this seem sensible to you?

**Comment by schlessera** [comment]
No, this should be handled with the following set of Composer options:
```
	"minimum-stability": "dev",
	"prefer-stable": true,
```

**Comment by danielbachhuber** [comment]
> No, this should be handled with the following set of Composer options

Like 46995f2c4dce484b7db84fc6fa2dcabf5e5d2b9c ?

**Comment by schlessera** [comment]
Yes. That should have the same effect, using the latest matching stable as far as possible, and falling back to `dev-master` if no stable fits the requirements.

**Pull request merged**
