### PR TITLE
Require minimum PHP 5.4

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #4554

### CODE REVIEW

**Comment by gitlost** [comment]
A bit premature to be doing this isn't it? I think this should be reverted pending discussion and preparation...

**Comment by danielbachhuber** [comment]
> A bit premature to be doing this isn't it? I think this should be reverted pending discussion and preparation...

Could you explain further? What additional discussion and preparation is needed?

**Comment by gitlost** [comment]
Well `scaffold package` will have to be updated and then all the packages for a start. Nothing can be built at the moment. Plus it's not clear to me this should be a hard requirement anyway

**Comment by danielbachhuber** [comment]
> Well `scaffold package` will have to be updated and then all the packages for a start.

Does that block this?

> Nothing can be built at the moment.

Can you point me to this issue?

> Plus it's not clear to me this should be a hard requirement anyway

Can you clarify further?

**Comment by gitlost** [comment]
> Does that block this?

This blocks building packages.

> Can you point me to this issue?

See https://github.com/wp-cli/extension-command/pull/89 and https://github.com/wp-cli/scaffold-command/pull/131 plus any other attempt to build a package now.

> Can you clarify further?

There is nothing in WP-CLI that requires PHP 5.4 for it to run. So a hard requirement is artificial.

**Comment by danielbachhuber** [comment]
> See wp-cli/extension-command#89 and wp-cli/scaffold-command#131 plus any other attempt to build a package now.

Ok, we can revert and come back to it. #4715

> There is nothing in WP-CLI that requires PHP 5.4 for it to run. So a hard requirement is artificial.

Yes, that's intentional.

**Pull request merged**
