### PR TITLE
Avoid variable assignments within statements

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #4058

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@wp-cli/committers Sorry about the delay, this is now cleaned up

**Comment by gitlost** [comment]
There's an issue here with a double file read (https://github.com/wp-cli/wp-cli/pull/4389/files#diff-96c026ad1c6dc030a7c7dfe32107aa0cR159).

But apart from that I don't think disallowing a time-honoured PHP paradigm like (https://github.com/wp-cli/wp-cli/pull/4389/files#diff-445ef2877063cddd8d2d17a2f58e44f7R133)
```
$positional_args = $assoc_args = $global_assoc = $local_assoc = array();
```
adds anything. Similarly this paradigm (https://github.com/wp-cli/wp-cli/pull/4389/files#diff-ebfa725722979f3a5e288bb8f86269a3L834), one of the most recognizable in the history of programming
```
while ( ( $line = fgets( STDIN ) ) !== false ) {
```

The rule for [Squiz.PHP.DisallowMultipleAssignments](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml#L326) cites [Clever Code](https://make.wordpress.org/core/handbook/coding-standards/php/#clever-code) but it's not in these cases, nor in most of the others.

**Comment by danielbachhuber** [comment]
> There's an issue here with a double file read (https://github.com/wp-cli/wp-cli/pull/4389/files#diff-96c026ad1c6dc030a7c7dfe32107aa0cR159).

Why is that an issue?

> But apart from that I don't think disallowing a time-honoured PHP paradigm like (https://github.com/wp-cli/wp-cli/pull/4389/files#diff-445ef2877063cddd8d2d17a2f58e44f7R133)

`¯\_(ツ)_/¯` I'm sure lots of people could debate various standards all day.

**Comment by gitlost** [comment]
> Why is that an issue?

Because it's needlessly reading the file twice.

**Comment by danielbachhuber** [comment]
In practicality, it's already taken some amount of time to work through all of these changes, so I'm not strongly motivated to go back and undo them.

**Comment by schlessera** [comment]
Of course this is all up for debate, just want to state that most of these changes are not necessarily for the better. The corresponding rule seems a bit simplistic.

**Comment by schlessera** [comment]
But I don't feel strongly about any of this. If it allows for having proper checks in place, I'm all for it.

**Comment by danielbachhuber** [comment]
> If it allows for having proper checks in place, I'm all for it.

Yes, this is the purpose of making the changes in the first place.

> Because it's needlessly reading the file twice.

Ok, updated in 867ec330

**Comment by danielbachhuber** [comment]
Landing this so we can move on.

**Comment by gitlost** [comment]
I'm deeply unhappy about this.

**Comment by danielbachhuber** [comment]
> I'm deeply unhappy about this.

Avoiding variable assignments within statements?

**Pull request merged**
