### PR TITLE
Site option support

### PR DESCRIPTION
**Pull request by trepmal**
First pass is basically a copy of the option command.

### CODE REVIEW

**Comment by szepeviktor** [comment]
May I finish this?

**Comment by danielbachhuber** [comment]
> May I finish this?

Sure — but it needs abstraction to a base class

**Comment by szepeviktor** [comment]
So the new class would be the common part of option.php and site.php?

**Comment by danielbachhuber** [comment]
> So the new class would be the common part of option.php and site.php?

Right... `Site_Option_Command` would extend the `CommandWithOption` abstraction.

**Comment by szepeviktor** [comment]
We need a compuster scientist to have it complished.

**Comment by szepeviktor** [comment]
Is it implemented somewhere?

**Comment by danielbachhuber** [comment]
No, but it's also tracked in #1628

**Pull request closed without merging**
