### PR TITLE
Add `after_invoke` hook for any post-execution tasks

### PR DESCRIPTION
**Pull request by danielbachhuber**
See #1761

### CODE REVIEW

**Comment by szepeviktor** [comment]
Could you add it [here](https://github.com/wp-cli/wp-cli/blob/115a0292066bbceb04979390027b03f1e17e53f0/php/class-wp-cli.php#L258) also?

**Comment by szepeviktor** [comment]
Have you notices that `$exit` is not used in `error()`?

**Comment by danielbachhuber** [comment]
> Could you add it here also?

Nope. If the command exits in any way, there's no way we can capture that action. You should be using a wrapper script.

**Comment by danielbachhuber** [comment]
> Have you notices that $exit is not used in error()?

Looks like a bug :)

**Comment by szepeviktor** [comment]
> Nope. If the command exits in any way, there's no way we can capture that action. You should be using a wrapper script.

Why is it impossible to add `after_invoke` in `error()`?

**Comment by szepeviktor** [comment]
BTW I have a complex wrapper: https://github.com/szepeviktor/wplib

**Comment by danielbachhuber** [comment]
> Why is it impossible to add after_invoke in error()?

Because I don't want to add the hook in every place the command code _could_ exit. It only logically makes sense in one spot.

**Comment by scribu** [comment]
> Nope. If the command exits in any way, there's no way we can capture that action.

What about [register_shutdown_callback()](http://php.net/manual/en/function.register-shutdown-function.php)?

**Comment by danielbachhuber** [comment]
> What about register_shutdown_callback()?

Could work, although I suppose we'd want to unregister after the command executes successfully.

**Comment by danielbachhuber** [comment]
I'm going to skip `register_shutdown_callback()` for now, and we can solve the problem of the hook not firing when it's actually a problem.

**Pull request merged**
