### PR TITLE
"installation" instead of "install"

### PR DESCRIPTION
**Pull request by grantpalin**
Per https://github.com/wp-cli/wp-cli/issues/4541 use "installation" instead of "install"

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@grantpalin Can you squash your commit please?

**Comment by danielbachhuber** [comment]
@grantpalin These don't look like separate pull requests...

**Comment by grantpalin** [comment]
When I make multiple commits on the same branch of my fork, they are auto pushed to the same PR. I don't get the chance to do separate PRs.

**Comment by grantpalin** [comment]
Maybe I'll start over with this pr

**Comment by danielbachhuber** [comment]
> When I make multiple commits on the same branch of my fork, they are auto pushed to the same PR. I don't get the chance to do separate PRs.

Right. You'll need to create separate branches for each PR.

**Pull request closed without merging**
