### PR TITLE
Test PHP 5.6 instead of 5.5 in plugin tests .travis.yml

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by szepeviktor** [comment]
> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP
Core still suffers from PHP 4 constructors?

**Comment by danielbachhuber** [comment]
> Core still suffers from PHP 4-style constructors?

Older versions of WordPress do.

**Comment by szepeviktor** [comment]
I thought it is WP trunk for PHP7.

**Comment by danielbachhuber** [comment]
> I thought it is WP trunk for PHP7.

Yes, but in the tests WP-CLI installs older versions of WordPress. When it does, the errors pop up.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
