### PR TITLE
Corrected Type Docs & Usage

### PR DESCRIPTION
**Pull request by XedinUnknown**
Addresses issue #5110.
Makes no functional changes, but only changes types to
match the expected behaviour.

After these fixes, the issues list looks [like this][phan_report].

[phan_report]: https://github.com/wp-cli/wp-cli/files/2999571/phan_report.txt

### CODE REVIEW

**Comment by schlessera** [comment]
@XedinUnknown It currently fails PHPCS checks because we still have some files in there that were never fixed up. I'll take a look at fixing this as soon as I find the time.

**Comment by XedinUnknown** [comment]
I may have also written non-compliant docs. Don't remember exactly what PHPCS say about that. Will take a look at the build log soon.

**Comment by XedinUnknown** [comment]
@schlessera, it was me, sorry. Tabs VS spaces... Please take another look :)

**Comment by schlessera** [comment]
Thanks for the PR!

**Pull request merged**
