### PR TITLE
Update Composer dependencies (2017-06-23)

### PR DESCRIPTION
**Pull request by wp-make-coffee**
```
Loading composer repositories with package information
Updating dependencies
Writing lock file
Generating autoload files
```

### CODE REVIEW

**Comment by schlessera** [comment]
@danielbachhuber There's no actual change here. I was under the impression the script only generates PRs when packages were updated. Did this change?

**Comment by wojsmol** [comment]
@schlessera There is chenge in https://github.com/Roave/SecurityAdvisories see https://github.com/wp-cli/wp-cli/pull/4179/files. The separate problem is that the script did not show the package as changed in PR coomment.

**Comment by schlessera** [comment]
Ah, good catch, @wojsmol.

Yes, I think that that package does some magic to always get updates in a forceful way.

**Comment by danielbachhuber** [comment]
> There's no actual change here. I was under the impression the script only generates PRs when packages were updated. Did this change?

No, it only generates PRs when there are changes.

**Pull request merged**
