### PR TITLE
Remove $pipes as are undefined and unaccessible in this context.

### PR DESCRIPTION
**Pull request by mattclegg**
I noticed this while working on another PR.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
`$pipes` is required by `proc_open()`

**Comment by mattclegg** [comment]
Ah yes, you are correct. It's weird that in the [documentation](http://php.net/manual/en/function.proc-open.php) there is a `&` before `$pipes` to suppress errors of it not being defined.

**Comment by danielbachhuber** [comment]
> there is a `&` before `$pipes` to suppress errors of it not being defined.

The `&` means "pass by reference". `@` is for suppressing errors.

**Comment by mattclegg** [comment]
Oh yeah sorry, I think I need another coffee..

**Pull request closed without merging**
