### PR TITLE
Create a new `wp contrib-list` command to list contributors

### LINKED ISSUE #3788: Improve GitHub contributor list generation script
We currently have a `utils/contrib-list` script which never correctly fetches the GitHub usernames.

Ideally, we'd have a script that could fetch release contributors for `wp-cli/wp-cli`, `wp-cli/handbook` and others.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #3788

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Build failing because https://github.com/wp-cli/wp-cli/issues/4087

**Comment by danielbachhuber** [comment]
Produces output like this:

```
wp --require=utils/contrib-list.php contrib-list --format=markdown
Current open wp-cli/wp-cli milestone: 1.2.0
Current open wp-cli/handbook milestone: 1.2.0
Closed wp-cli/db-command milestone(s): 1.0.1
Closed wp-cli/media-command milestone(s): 1.0.1
Closed wp-cli/server-command milestone(s): 1.0.4, 1.0.3, 1.0.2, 1.0.1
Closed wp-cli/entity-command milestone(s): 1.0.1
Closed wp-cli/extension-command milestone(s): 1.0.2, 1.0.1
Closed wp-cli/config-command milestone(s): 1.1.0
Closed wp-cli/scaffold-command milestone(s): 1.0.3, 1.0.2, 1.0.1
[aaemnnosttv](https://github.com/aaemnnosttv), [afragen](https://github.com/afragen), [balbuf](https://github.com/balbuf), [behzod](https://github.com/behzod), [carl-alberto](https://github.com/carl-alberto), [CodeProKid](https://github.com/CodeProKid), [danielbachhuber](https://github.com/danielbachhuber), [diablodale](https://github.com/diablodale), [diggy](https://github.com/diggy), [dnmvisser](https://github.com/dnmvisser), [fjarrett](https://github.com/fjarrett), [flaskboy](https://github.com/flaskboy), [geekoun](https://github.com/geekoun), [gitlost](https://github.com/gitlost), [hason](https://github.com/hason), [JayWood](https://github.com/JayWood), [jeremyfrady](https://github.com/jeremyfrady), [ka7](https://github.com/ka7), [kcarwilemiller](https://github.com/kcarwilemiller), [lichtscheu](https://github.com/lichtscheu), [mbovel](https://github.com/mbovel), [MiteshShah](https://github.com/MiteshShah), [miya0001](https://github.com/miya0001), [ntwb](https://github.com/ntwb), [rahul3883](https://github.com/rahul3883), [raquelmsmith](https://github.com/raquelmsmith), [Rarst](https://github.com/Rarst), [ryanshoover](https://github.com/ryanshoover), [schlessera](https://github.com/schlessera), [Sidsector9](https://github.com/Sidsector9), [SosyalAlkolik](https://github.com/SosyalAlkolik), [ssnepenthe](https://github.com/ssnepenthe), [Steveorevo](https://github.com/Steveorevo), [tfrommen](https://github.com/tfrommen), [tillkruss](https://github.com/tillkruss), [timdream](https://github.com/timdream), [trepmal](https://github.com/trepmal), [wp-make-coffee](https://github.com/wp-make-coffee), [zacksheppard](https://github.com/zacksheppard)
```

**Comment by schlessera** [comment]
Does it make sense to filter `wp-make-coffee`?

**Comment by danielbachhuber** [comment]
> Does it make sense to filter `wp-make-coffee`?

I was thinking it'd be a fun easter egg.

**Pull request merged**
