### PR TITLE
Implement CS checking based on the `WP_CLI_CS` ruleset

### LINKED ISSUE #5166: Adopt and enforce new `WP_CLI_CS` standard
We have a new PHPCS standard for WP-CLI called `WPCliCS` (props @jrfnl). It is part of the `wp-cli/wp-cli-tests` package starting with version v2.1.0.

To adopt & enforce this new standard, the following actions need to be taken for this repository:

- [ ] Create a PR that adds a custom ruleset `phpcs.xml.dist` to the repository

    - Add `phpcs.xml.dist` file
    - Adapt `.distignore` to ignore `phpcs.xml.dist` & `phpunit.xml.dist`
    - Adapt `.gitignore` to ignore `phpunit.xml`, `phpcs.xml` & `.phpcs.xml`
    - Require version `^2.1` of the `wp-cli/wp-cli-tests` as a dev dependency
- [ ] Make any required changes to the code that fail the checks from the above ruleset in separate PRs
- [ ] Merge thre ruleset once all required changes have been processed and merged

A sample PR for a simple repository can be seen here: https://github.com/wp-cli/maintenance-mode-command/pull/3/files

Related https://github.com/wp-cli/wp-cli/issues/5179

### PR DESCRIPTION
**Pull request by jrfnl**
This basically updates the PHPCS ruleset to use the new `WP_CLI_CS` standard and adds a number of whitelist comments and exclusions.

As annotated in issue #5166, there is currently only one issue still remaining to be fixed:
```
FILE: php\utils-wp.php
------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
------------------------------------------------------------------------------------------
 111 | WARNING | strip_tags() is discouraged. Use the more comprehensive
     |         | wp_strip_all_tags() instead.
     |         | (WordPress.WP.AlternativeFunctions.strip_tags_strip_tags)
------------------------------------------------------------------------------------------
```

Please see the individual commits for more detail.

N.B.: In contrast to some of my other PRs, the commits in this PR should probably not be squashed.

Fixes #5166 

Relates to https://github.com/wp-cli/wp-cli/issues/5179

### Composer: use wp-cli-tests ^2.1

... as that version contains the new WPCliCS PHPCS standard.

Includes updating the `composer.lock` file with `composer update wp-cli/wp-cli-tests --with-all-dependencies` which resulted in the following updates:
```
  - Removing phpcompatibility/phpcompatibility-wp (1.0.0)
  - Updating wp-coding-standards/wpcs (1.2.1 => 2.1.0)
  - Updating wp-cli/eval-command (v2.0.3 => v2.0.4)
  - Updating wp-cli/config-command (v2.0.2 => v2.0.3)
  - Updating phpcompatibility/php-compatibility (8.2.0 => 9.1.1)
  - Removing wp-cli/wp-cli-tests (v2.0.13)
  - Installing wp-cli/wp-cli-tests (v2.1.1)
  - Updating roave/security-advisories (dev-master 9c6c45a => dev-master 1b329f4)
```

### .gitignore: ignore correct phpcs/phpunit config files

* Remove refs which shouldn't be in this file.
    - The `phpunit.xml.dist` file shouldn't be ignored.
    - The two directory entries look like personal ones which shouldn't have gotten into the `.gitignore` file in the first place, but should have been put into someone's personal `.git/info/exclude` file.
* Add files which allow devs to overwrite config files for PHPUnit and PHPCS
    - The `.dist` files should be committed. However, for their personal use, devs can overrule those files with versions without `.dist`.
        Those personal versions should never be committed.

As a side-note: for PHPCS, having a personal version while still using the original `.dist` file is made very easy, as you can just import the `.dist` file as a starting point, like so:
```xml
<?xml version="1.0"?>
<ruleset name="WP-CLI">
    <rule ref="./phpcs.xml.dist"/>
</ruleset>
```

### PHPCS: update the ruleset/defer to WPCliCS

The file is completely documented in-line.

### PHPCS: replace some WPCS whitelist comments with PHPCS whitelist comments

The WPCS native whitelist comments have been deprecated in WPCS 2.0 and will be removed in 3.0, in favour of the PHPCS native selective ignore comments which were introduced in PHPCS 3.2.

### PHPCS: whitelist some code for select sniffs 

Depends on #5199

### CODE REVIEW

**Comment by schlessera** [comment]
Tackling that last remaining issue now...

**Comment by schlessera** [comment]
Depends on #5199

**Comment by jrfnl** [comment]
Rebased now #5199 has been merged. Fingers crossed the build should pass.

**Comment by schlessera** [comment]
@jrfnl Looks like it is failing on a bug in PHPCS: https://travis-ci.org/wp-cli/wp-cli/jobs/523862847#L595

**Comment by jrfnl** [comment]
> Looks like it is failing on a bug in PHPCS

My bad. I whitelisted the wrong file: https://github.com/wp-cli/wp-cli/pull/5198/files#diff-6758ef1f416bd888bd1a5cad8f97cc2bR119

Should be fixed now.

**Comment by jrfnl** [comment]
*LOL* Ok, so I hadn't whitelisted the wrong file, except since I last scanned, the same issue is now being reported for a second file....

As this relates to a bug in PHPCS itself, I've now just chosen to exclude that complete error code for the time being with a note that that exclusion should be removed once PHPCS 3.5.0 has been released and starts to be used.

**Comment by jrfnl** [comment]
Builds are :heavy_check_mark: :tada:

**Pull request merged**
