### PR TITLE
Caching the vendor itself looks like a bad idea

### PR DESCRIPTION
**Pull request by szepeviktor**
https://github.com/travis-ci/travis-ci/issues/4579#issuecomment-127972205

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks @szepeviktor. I think I've experienced why this is a bad idea previously (builds randomly failing because of bad cache), but never connected the dots.

**Comment by szepeviktor** [comment]
You're welcome.

**Comment by szepeviktor** [comment]
@danielbachhuber Many WP-CLI repos have the vendor cached. Could you figure out a way to "mass-check" their Travis config?

**Comment by danielbachhuber** [comment]
> Many WP-CLI repos have the vendor dir. cached. Could you figure out a way to "mass-check" their Travis config?

Yes, we'll fix with https://github.com/wp-cli/scaffold-package-command/pull/160

**Pull request merged**
