### PR TITLE
Add skipped functions to wp-cli.yml

### PR DESCRIPTION
**Pull request by 1Pauletto**
Hello! At my work we have a case, if client has functions in wp-config.php like add_filter, is_admin and other wp-cli failed when trying to read config, because it nows nothing about these function.

So what I've done:

1) I add an options for wp-cli.yml and If user has any functions you have to put to your wp-cli.yml below code: 
```
wp-config-stub-functions:
    is_admin: 'false'
    add_filter: 'false'
    apply_filters: 'false'
```
*wp-config-stub-functions is an array, where keys are functions which we want to make stubs and values are return values for stubs functions

2) Runner execute get_wp_config_code function, and this function has checking, if there are some skipped function in wp-cli.yml it will add stubs for them.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Hi @1Pauletto,

Thanks for the pull request. I think this use case would be better handled with WP-CLI's [hook system](https://make.wordpress.org/cli/handbook/internal-api/wp-cli-add-hook/), instead of adding function definitions to `wp-cli.yml`. Thoughts?

**Comment by schlessera** [comment]
I think the use case you need this pull request for seems to be as a case of misusing the `wp-config.php` file. That file is meant to prepare WordPress to be loaded, so using the WordPress Plugin API inside of that file is not the right way to go.

**Comment by 1Pauletto** [comment]
@schlessera  of course you are right, but we use wp-cli for our clients, and we can not be sure that they don't have these functions in their wp-config.php.

**Comment by 1Pauletto** [comment]
And the main point, that we have clients with stable work sites, who wrote to wp-config code with functions, that I described.

**Comment by schlessera** [comment]
@1Pauletto I understand that you want to work with whatever your clients can come up with. However, when it comes to WP-CLI, we as the maintainers have to draw a line somewhere.

Imagine we add this functionality now, meaning *we* need to take care of maintaining this part of the code indefinitely, and everything that would result out of it. Now, what if your client adds one of the WP classes next? We'd need to add another set of functionality to stub out classes.

This cycle of clients adding the wrong stuff and WP-CLI adapting could go on indefinitely, with WP-CLI growing technical debt to support misuses of the `wp-config.php` file.

You can probably agree that this is not the direction we want to take for the long-term evolution of WP-CLI.

I'd suggest you head on over to our #cli Slack team to discuss how to solve your particular issue without degrading the WP-CLI core. I'm sure we can find a solution that you can use locally for your specific needs.

**Comment by 1Pauletto** [comment]
Ok, thank you.

**Pull request closed without merging**
