### PR TITLE
Db: add missing trailing period in command messages

### PR DESCRIPTION
**Pull request by ernilambar**
See #2848

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ernilambar There's a merge conflict now that needs to be resolved.

Also, I'm not sure how I feel about:

> Success: Exported to wordpress_dbase.sql.

The period in the sentence confuses the filename. Should we be quoting filenames? Mind taking a look at a few other open source projects to see how they handle this case?

**Comment by ernilambar** [comment]
In Regenerate thumbnails, file names are wrapped by double apostrophe.
```
"cropped-triforce-wallpaper.jpg" (ID 1700) was successfully resized in 0.369 seconds.
"spectacles" (ID 1692) was successfully resized in 0.164 seconds.
```

In Apache errors, filenames are wrapped with small brackets.

`description: The requested resource (/MyApp/init) is not available.`

Windows generates errors like this.
`Can't rename "Pictures" because a file or folder with name already exists.`

Some app uses error messages like this.
`Cannot create file C:\WINDOWS\system32\shell32.dll.`
http://prntscr.com/bi5q05

Archive app.
`Unable to expand "scip-3.2.0.tgz" into "Desktop".`
http://prntscr.com/bi5rfm

So, generally in success/error messages, filenames and folder names are wrapped with some character. We could also use something like that. May be `"` or `'`.

**Comment by danielbachhuber** [comment]
> So, generally in success/error messages, filenames and folder names are wrapped with some character. We could also use something like that. May be " or '.

Ok. Let's wrap filenames in quotes.

**Comment by ernilambar** [comment]
@danielbachhuber for confirmation, which are we going to use `"` or `'`? This applies to both filename and folder name, right?

**Comment by danielbachhuber** [comment]
> for confirmation, which are we going to use " or '

Always use `'`, unless you need to use `"` (e.g. there's a `'` within the string you want to quote).

> This applies to both filename and folder name, right?

Yes

**Comment by ernilambar** [comment]
I tried to merge conflict and fix issues. Is this right approach for fixing merge conflict? If not, I will create new PR.

**Comment by danielbachhuber** [comment]
> Is this right approach for fixing merge conflict? If not, I will create new PR.

I think the history got messed up somehow. Let's go with a new PR — thanks

**Pull request closed without merging**
