### PR TITLE
Allowed numbers to subcommand Sanitizing

### LINKED ISSUE #4159: @subcommand Sanitizing
When a subcommand or alias is specified using the function documentation markup (e.g. `@subcommand xyz` or `@alias xyz`), values containing a number are terminated wherever that number occurs.

For example, I have a class that is registered as a command, and within that class a public function called `revoke_md5_passwords()`. But I want users to access it via "revoke-md5-passwords", so added `@subcommand revoke-md5-passwords` to the function docs. The subcommand that ends up being registered is just "revoke-md".

The subcommand registration does, however, work fine if explicitly calling
`WP_CLI::add_command(
	'foo bar revoke-md5-passwords',
	$functionvar
);`

Long story short, it seems different command name sanitizing is happening depending on how that value makes its way into the system. :)

### PR DESCRIPTION
**Pull request by chetansatasiya**
Fixes #4159

### CODE REVIEW

**Comment by chetansatasiya** [comment]
I have added my PR to allow the numbers into the subcommand Sanitizing.

@danielbachhuber & @schlessera Please let me know if any changes in my PR

**Comment by schlessera** [comment]
@chetansatasiya Please add a test case to check for actually adding such a subcommand.

**Comment by schlessera** [comment]
@chetansatasiya In case you don't know how to proceed with the tests, here's a brief overview: https://make.wordpress.org/cli/handbook/pull-requests/#running-and-writing-tests .

Let me know if you need any additional guidance!

**Comment by danielbachhuber** [comment]
I've added a test in 38285acf

**Comment by schlessera** [comment]
Test seemed to have randomly failed for PHP 5.6, restarted...

**Pull request merged**
