### PR TITLE
Update README.md to indicate Github issues are no longer for support

### PR DESCRIPTION
**Pull request by danielbachhuber**

### CODE REVIEW

**Comment by grappler** [comment]
Have you thought about adding a link to `CONTRIBUTING.md` or create an `ISSUE_TEMPLATE` with a bit of text?

**Comment by danielbachhuber** [comment]
> Have you thought about adding a link to CONTRIBUTING.md or create an ISSUE_TEMPLATE with a bit of text?

Those would be good additions too.

**Comment by szepeviktor** [comment]
@danielbachhuber Could you tell me the reason?

**Comment by danielbachhuber** [comment]
> Could you tell me the reason?

The reason that Github issues are no longer for general support questions?

If so, it's because I no longer want to offer general support through Github issues. As more people use WP-CLI and ask general usage questions, offering free support through Github issues becomes more of a burden and less sustainable. We need to keep the issue backlog focused on bug reporting and enhancements.

**Comment by szepeviktor** [comment]
> As more people use WP-CLI and ask general usage questions

I thought.
Thanks.

**Pull request merged**
