### PR TITLE
Support Phive package manager

### PR DESCRIPTION
**Pull request by schlessera**
Phive needs a GPG signature as `.phar.asc` file.

See https://phar.io/howto/sign-and-upload-to-github.html

### CODE REVIEW

**Comment by schlessera** [comment]
This will probably not work as is, as GitHub/Travis does not have my private GPG key, GitHub only has the public one.

The private key is needed to sign something, however.

For a proper solution: https://stackoverflow.com/questions/45188811/how-to-gpg-sign-a-file-that-is-built-by-travis-ci

**Comment by gitlost** [comment]
So leave this for now and do manually as you suggest on slack some time after release?

**Comment by schlessera** [comment]
@miya0001 This was not meant to be merged, as it will not work. GPG does not have a corresponding private key on the Travis side.
I'm reverting this for now.

**Comment by schlessera** [comment]
Discussion should happen here: #4659

**Pull request merged**
