### PR TITLE
Added field filtering in cron event list command.

### LINKED ISSUE #2666: Add [--<field>=<value>] to wp cron event list
In a site with lots of events it would be useful to filter the hook:

```
wp cron event list --hook=my-custom-event
```

### PR DESCRIPTION
**Pull request by gedex**
Resolves #2666.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks for the pull request! Can you please add [functional tests](http://wp-cli.org/docs/pull-requests/#functional-tests)?

**Comment by danielbachhuber** [comment]
Closing in favor of #2674

**Comment by gedex** [comment]
Sorry for late reply, was distracted by other things. Thanks for adding the tests!

**Comment by danielbachhuber** [comment]
You're welcome :) Happy to help

**Pull request closed without merging**
