### PR TITLE
On Travis, serve Github update check requests from cache

### PR DESCRIPTION
**Pull request by danielbachhuber**
This will prevent us from hitting the API request rate-limiting.

When `WP_CLI_REQUESTS_CACHE_DIR` environment variable is set, check to
see if a cached version of the request is available from the static file
cache. If the cached version is available, serve it. If it's not
available, do the request and stash it in the cache.

Ideally, we'd be injecting our own `Requests_Transport` class, but
`Requests` doesn't easily support this.

See #1612

### CODE REVIEW

**Comment by rmccue** [comment]
> Ideally, we'd be injecting our own Requests_Transport class, but

Would `Requests::add_transport` work for this? It's also possible to set `Requests::$transport` (an array) directly to override, but that's semi-internal behaviour. Happy to add extra methods if needed here.

**Comment by danielbachhuber** [comment]
I looked at `add_transport()` but merging arrays adds my transport to the end of the stack. `set_transport()` would work, and built-in request cache would be even better. I need a solution in the near term though.

**Comment by rmccue** [comment]
> I looked at `add_transport()` but merging arrays adds my transport to the end of the stack. `set_transport()` would work, and built-in request cache would be even better. I need a solution in the near term though.

Sounds like we need a priority argument for the transports.

In this specific case, could you set `$options['transport'] = new ...` (or `= 'ClassName'`, either way) directly? Looks like it's only this invocation that needs changing.

**Comment by danielbachhuber** [comment]
I'm going with this PR to start, as this is an immediate problem we need to solve.

**Pull request merged**
