### PR TITLE
Accept multiple term IDs in term url

### PR DESCRIPTION
**Pull request by ernilambar**
See #2863

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@ernilambar Can you include updated tests please?

**Comment by ernilambar** [comment]
@danielbachhuber Can you please check the build result? What did I do wrong :-) 
https://travis-ci.org/wp-cli/wp-cli/jobs/133088641#L295

**Comment by danielbachhuber** [comment]
@ernilambar Does it fail locally?

**Comment by ernilambar** [comment]
@danielbachhuber I have fixed the test. I had used two STDOUT variables `{TERM_ID_1}` and `{TERM_ID_2}`. But somehow ``{TERM_ID_2}` was not being replaced with the term ID. So that was giving WP_Error.

**Pull request merged**
