### PR TITLE
Include more files in `wp-settings-cli.php` in prep for WP 4.4

### PR DESCRIPTION
**Pull request by danielbachhuber**
Without including these files, WP-CLI will fatal when trying to load WordPress.

See https://core.trac.wordpress.org/changeset/35718#file17

Also updates `Utils\maybe_require()` to handle `$wp_version` with
`-src` in the value. See #2164

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Build fails because I'm waiting on a new nightly build

**Comment by nacin** [comment]
I pushed a new nightly build. Didn't notice the new commits to switch over. That seems fine, too.

**Comment by szepeviktor** [comment]
Could there be a warning of incompatible WP version?

**Comment by danielbachhuber** [comment]
> Could there be a warning of incompatible WP version?

Where?

**Comment by szepeviktor** [comment]
Oh! I haven't thought about it.
My answer would have been: *In old wp-cli-s.*

**Pull request merged**
