### PR TITLE
Remove requirement for `--url`

### PR DESCRIPTION
**Pull request by mattclegg**
This loads the default url from the database if a multisite isn't defined by wp-config.php/sunrise.php

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Hm. I'm not quite sure what this is an attempt to solve, and that this the best way to solve it.

To help move the conversation forward, can you provide a Behat test case for the change and a bit more detail on what you're trying to do?

**Comment by mattclegg** [comment]
It is to solve having to use "--url" by defaulting to whatever url is in the database (without having to know whatever that maybe) https://github.com/wp-cli/wp-cli/issues/2215

**Comment by danielbachhuber** [comment]
#2215 is going to be solved in a different way. 

For multisite, WP-CLI already knows to look for `DOMAIN_CURRENT_SITE` in your wp-config.php if no `--url` parameter is provided. This seems to have been sufficient to date. Can you explain why we need to change to making a database request?

**Comment by mattclegg** [comment]
It removes the requirement to have 'DOMAIN_CURRENT_SITE' defined in wp-config. Additionally when migrating a database between different urls then the url in the database might not match.

__For example:__
If I have a multiple urls of the same site. ie production and test;
* http://www.example.com
* http://test.example.com

I can copy the database from 'www' to 'test' and then I want to update the site work under the new url by running something like; `wp --network search-replace http://www.example.com http://test.example.com`
However `wp-cli` will fail saying "Error: Site  not found." I need to use the `--url` parameter even though the url in the database might be completely unrelated to what is in wp-config.

**Comment by danielbachhuber** [comment]
> It removes the requirement to have 'DOMAIN_CURRENT_SITE' defined in wp-config.

I see. We aren't going to change this requirement at this time. 

>  Additionally when migrating a database between different urls then the url in the database might not match.

Right, which is a problem of `wp search-replace` and not the general bootstrap process.

**Comment by mattclegg** [comment]
It causes the same problem for any wp-cli plugins that also rely on `--url` so it's not just specific to `wp search-replace`.

Is there a problem with loading with loading the url from the database if one hasn't been defined?

I can create a Behat test case if this helps?

**Pull request closed without merging**
