### PR TITLE
Fix breaking multi-line CSV values on reading

### PR DESCRIPTION
**Pull request by Takshil-Kunadia**
Fixes https://github.com/wp-cli/wp-cli/issues/5412

### CODE REVIEW

**Comment by thelovekesh** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/5935

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
Thanks for the PR, @Takshil-Kunadia !

Can you include some tests for this change?

**Comment by Takshil-Kunadia** [comment]
Thanks! @danielbachhuber . I have added Unit test for CSV Iterator and added basic tests along with the test that covers the intended scenario. Please review...

**Review by mrsdizzie — APPROVED** [review]

**Review by danielbachhuber — APPROVED** [review]
Thanks for the PR and the tests!

**Pull request merged**
