### PR TITLE
travis-ci: test with WordPress 4.1

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Thanks! Can you drop 4.0 then?

**Comment by Ramoonus** [comment]
Yes and no
Not if you want to keep it supported

**Comment by danielbachhuber** [comment]
We only need to support the latest version of WordPress

**Comment by Ramoonus** [comment]
then you can drop ...

**Comment by danielbachhuber** [comment]
#1643

**Pull request closed without merging**
