### PR TITLE
Parse plugin readme.txt to find WP versions to test for plugin-tests scaffold

### LINKED ISSUE #423: plugin-tests scaffold needs to respect plugin supported versions
Specifically, when generating the travis.yml, the WordPress versions tested should be those versions supported by the plugin.

### PR DESCRIPTION
**Pull request by gilbitron**
Fixes #423

Hey guys. Hope you don't mind me picking this up and having a go. Over at [Delicious Brains](https://deliciousbrains.com/) we each have a "contrib" day once a month and I'm considering contributing to WP-CLI when I can (because I love it and use it all the time).

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Can you write a functional test for this?

See https://github.com/wp-cli/wp-cli/blob/master/CONTRIBUTING.md

**Comment by gilbitron** [comment]
Sure. I've never used behat but I'll give it a go.

**Comment by gilbitron** [comment]
Done.

**Comment by danielbachhuber** [comment]
Thanks!

**Pull request merged**
