### PR TITLE
Respect `WP_DEBUG_DISPLAY` when Xdebug is enabled.

### LINKED ISSUE #3220: Respect WP_DEBUG instead of overriding
Currently the value of `display_errors` is overridden by `\Utils\wp_debug_mode()`, but I would expect WP_CLI to respect the value set by `WP_DEBUG`  and `\wp_debug_mode()` instead.

It sounds like [there may have once been a reason for overriding it](https://github.com/wp-cli/wp-cli/issues/706#issuecomment-236629262), but it's not known anymore.

In my experience, having it overridden is a hassle, because when I'm writing commands I don't have notice/warning/error messages easily available. In many cases, it might not even be obvious that an error occurred at all. So I have to manually check log files or [use a fragile workaround](https://github.com/iandunn/wp-cli-plugin-active-on-sites/blob/7b0d2e6/wp-cli-plugin-active-on-sites.php#L57) to restore the original settings.

I'd be happy to work on a PR if it's decided that this behavior should be removed.

Background information:

[php/utils-wp.php#L26](https://github.com/wp-cli/wp-cli/blob/7845a67b97c162573212b6bcf6aff62bfad2957c/php/utils-wp.php#L26)
cb57cc0
#786

### PR DESCRIPTION
**Pull request by iandunn**
This is a WIP to fix #3220. Right now it just adds the test to demonstrate the bug. It still needs another commit to actually fix the problem, but I ran out of time while digging into the best approach for that.

The scenario is a modified version of https://github.com/wp-cli/wp-cli/pull/3372; it just needed to be updated to match the PHP  7 error string.

### CODE REVIEW

**Comment by schlessera** [comment]
The test breaks for an unrelated reason: With debug output enabled, you get a notice on WP3.7 because it uses the old `mysql_connect()`. You could circumvent this by adding a `@require-wp-3.9` tag to the test.

**Comment by iandunn** [comment]
Thanks, 153c57d fixes that.

**Comment by schlessera** [comment]
@iandunn Are you still looking into this?
The test was meant to provoke a failure, but it currently passes.
This means that either we're testing the wrong thing or in a wrong way, or the bug we're trying to provoke is not reproducible within Travis.

**Comment by iandunn** [comment]
> Are you still looking into this?

It's still on my list, but there are lots of other things on my plate too. It's something I plan on doing eventually, but it's not a priority for today, and I don't have a specific ETA or deadline for it. 

If having an open PR bugs you, feel free to close it and I can re-open it once I get it to the next step.

> The test was meant to provoke a failure, but it currently passes.

It fails on my system, so I'm guessing it's just a difference between my environment and Travis. The scenario has some statements in the `wp-cli.yml` file that attempt to simulate Xdebug being enabled, and they work on my system (when I disable Xdebug), but maybe they don't work in Travis?

```bash
> behat --name="WP_DEBUG"

OS:	Darwin 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64
Shell:
PHP binary:	/usr/local/bin/php
PHP version:	7.1.12
php.ini used:	/usr/local/etc/php/7.1/php.ini
WP-CLI root dir:	/Users/iandunn/vhosts/tools/wp-cli
WP-CLI vendor dir:	/Users/iandunn/vhosts/tools/wp-cli/vendor
WP_CLI phar path:
WP-CLI packages dir:
WP-CLI global config:
WP-CLI project config:
WP-CLI version:	2.0.0-alpha

WordPress 4.9.4

Feature: Global flags

  @require-wp-3.9
  Scenario: Debug respects `WP_DEBUG` defined to true                                                                                   # features/flags.feature:100
    Given an empty directory                                                                                                            # features/steps/given.php:8
    And WP files                                                                                                                        # features/steps/given.php:55
    And a test.php file:                                                                                                                # features/steps/given.php:36
      """
      <?php
      echo "hello";
      calling_function_that_doesnt_exist();
      """
    And a wp-cli.yml file:                                                                                                              # features/steps/given.php:36
      """
      core config:
        extra-php: |
          define( 'WP_DEBUG', true );
          define( 'WP_DEBUG_DISPLAY', true );
          define( 'WP_CLI_FORCE_BEHAT_ERROR_REPORTING', false );

          // Simulate Xdebug being enabled.
          if ( ! function_exists( 'xdebug_debug_zval' ) ) {
            function xdebug_debug_zval() {}
          }

          ini_set( 'xdebug.force_display_errors', 'Off' );
      """
    When I run `wp core config {CORE_CONFIG_SETTINGS}`                                                                                  # features/steps/when.php:29
    And I run `wp db create`                                                                                                            # features/steps/when.php:29
    And I run `wp core install --url=wp.dev --title="WP Dev" --admin_user=wpcli --admin_password=wpcli --admin_email=wpcli@example.com` # features/steps/when.php:29
    Then STDOUT should not be empty                                                                                                     # features/steps/then.php:138
    When I run `wp eval 'echo var_dump( constant( "WP_DEBUG" ) );'`                                                                     # features/steps/when.php:29
    Then STDOUT should contain:                                                                                                         # features/steps/then.php:15
      """
      bool(true)
      """
    And STDERR should be empty                                                                                                          # features/steps/then.php:127
    When I try `wp eval-file test.php`                                                                                                  # features/steps/when.php:29
    Then the return code should be 255                                                                                                  # features/steps/then.php:7
    And STDOUT should be:                                                                                                               # features/steps/then.php:15
      """
      hello
      """
    And STDERR should contain:                                                                                                          # features/steps/then.php:15
      """
      Call to undefined function calling_function_that_doesnt_exist()
      """
      $ wp eval-file test.php
      hello
      cwd: /var/folders/vj/szwk8wpx2sqbcxx6x62wzwzc0000gn/T/wp-cli-test-run-flags.feature.100-5ac3aaa8e45cb7.15998191/
      run time: 0.27728700637817
      exit status: 255

1 scenario (1 failed)
15 steps (14 passed, 1 failed)
0m3.768s
```

**Comment by schlessera** [comment]
> If having an open PR bugs you, feel free to close it and I can re-open it once I get it to the next step.

Not at all, and no pressure. Just wanted to see whether there's still interest. All good.

> It fails on my system, so I'm guessing it's just a difference between my environment and Travis. The scenario has some statements in the wp-cli.yml file that attempt to simulate Xdebug being enabled, and they work on my system (when I disable Xdebug), but maybe they don't work in Travis?

Ah, for the tests we use `phpenv` to disable the `xdebug` extension being loaded. So the `ini_set` probably doesn't work because at that point, `xdebug` was not loaded and doesn't exist.

To make this work, we would have to use a different mechanism of disabling `xdebug`...

**Comment by schlessera** [comment]
Gentle ping to see if you're still interested in looking into this, @iandunn .

**Comment by iandunn** [comment]
I still think it should be fixed, but I haven't been able to find the time to finish it.

**Comment by ahberg** [comment]
Yes wp-cli should respect WP_DEBUG_DISPLAY. Do we really need a Travis test case? How can we move on?

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/48f17f23a198556bea815e2c03c6b5e5 in case this PR is auto-closed or broken in some way.

**Pull request closed without merging**
