### PR TITLE
Switch to Trusty on Travis

### PR DESCRIPTION
**Pull request by szepeviktor**

### CODE REVIEW

**Comment by szepeviktor** [comment]
I think we are all green, except there's no PHP 5.3 in that container.

**Comment by danielbachhuber** [comment]
I don't want to run Trusty during the beta period. It's not worth it to have to spend time tracking down why the build is randomly failing.

**Comment by szepeviktor** [comment]
Me neither, just couldn't resist trying out the solution from travis issue.


-- 
+36204242498
Ezen a készüléken sok az elütés. 
Elnézést!

**Comment by szepeviktor** [comment]
Later on PHP 5.3 will need Ubuntu precise
```yaml
matrix:
  include:
    - php: 5.3
      dist: precise 
```

**Pull request closed without merging**
