### PR TITLE
Skip associative arguments that were already provided on `--prompt`

### LINKED ISSUE #4762: `--prompt` should skip flags that have been included in the command
When running a command with the `--prompt` flag, any other flags that are passed to the command (either positional or associative) should be skipped in the prompt.

Example:

`wp core install --admin_email=email@example.com --prompt`

This command should skip the `admin_email` field when prompting the user for input.

### PR DESCRIPTION
**Pull request by schlessera**
I'm ignoring positional arguments for now and concentrate on associative arguments, except the ones of type `generic` (`--<field>=<value>`).

The current PR seems to work as expected, however I'm not sure yet how to write a test for this functionality.

Fixes #4762

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> As this is an interactive tool and not trivial to test, I'll merge this without test for now.

I think it probably should have a test. There are some existing examples in https://github.com/wp-cli/wp-cli/blob/ed4b892dfad613b35ca54c62d4be3677a861f798/features/prompt.feature

Essentially, you can pipe a `< SESSION` file into STDIN to drive the interactive session.

**Comment by schlessera** [comment]
Yes, that's what I thought as well, but I couldn't get this to work across multiple arguments, which is needed here.

I'll have another go, maybe I messed it up somewhere along the way...

**Comment by schlessera** [comment]
😊 I found out why it didn't work... I forgot to actually pipe the file in the final call.

**Comment by schlessera** [comment]
Ok, I added support for positional arguments and made the test work.

**Pull request merged**
