### PR TITLE
Revert "Move `RecursiveDataStructureTraverser` to `wp-cli/wp-cli` package"

### PR DESCRIPTION
**Pull request by danielbachhuber**
Reverts wp-cli/wp-cli#5864
See https://github.com/wp-cli/wp-cli/issues/5837

Let's have this live in its own repository

### CODE REVIEW

**Comment by schlessera** [comment]
@danielbachhuber What's the reasoning behind creating a separate repository for this? This will add a whole heap of extra effort (package setup, release process, test setup & CI/CD, etc...). For these few files, why not just stick with adding it to the package that is the "framework" package? Did you see a specific use case for using this outside of WP-CLI?

**Comment by danielbachhuber** [comment]
> What's the reasoning behind creating a separate repository for this?

@schlessera So we can start using the classes right away, instead of waiting for the framework to be tagged, dealing with back compat, etc.

> This will add a whole heap of extra effort (package setup, release process, test setup & CI/CD, etc...).

Our automation should solve this, no?

**Comment by schlessera** [comment]
> @schlessera So we can start using the classes right away, instead of waiting for the framework to be tagged, dealing with back compat, etc.

I usually deal with this by pulling in the `main` branch of the framework where needed, that's why they all come with a branch alias. During the release process, this is all corrected with stable tagged versions again.

> Our automation should solve this, no?

Every package not only adds extra maintenance overhead and slows down CI/CD, but also introduces a new "API" in the form of an officially accessible package that has its own versioning/dependency tree hassles.

**Comment by schlessera** [comment]
Moreover, I'd like to add that we cannot add a new package every time the framework would require an update that needs to immediately be accessible to a command repository.

**Comment by danielbachhuber** [comment]
> I usually deal with this by pulling in the `main` branch of the framework where needed, that's why they all come with a branch alias. During the release process, this is all corrected with stable tagged versions again.

@schlessera Ok, can you own setting this up? It sounds more complicated than what I proposed, but I don't have a strong opinion about this.

**Comment by schlessera** [comment]
@danielbachhuber I set this up. It's not complicated at all, as all packages are already configured, it just means bumping the minimu framework version in the corresponding packages to a not-yet-released version (which then automatically pulls in `dev-main`). I added some further explanation here: https://github.com/wp-cli/entity-command/pull/442#issuecomment-1810037170

**Pull request merged**
