### PR TITLE
remove unnecessary conditional execution

### PR DESCRIPTION
**Pull request by miya0001**
`$runtime_config` is undefined at all times.

Thanks! 😄

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> $runtime_config is undefined at all times.

I suspect this means `wp --config=config.yml` is broken, and has been for some time :(

**Comment by danielbachhuber** [comment]
> I suspect this means wp --config=config.yml is broken, and has been for some time :(

Yep, it's been broken since 7a1499e0a3683f9d51dc18d73d8b087685a9e318 (v0.13.0)

**Comment by miya0001** [comment]
I will make time and challenge to fix it. 😄

**Comment by danielbachhuber** [comment]
> I will make time and challenge to fix it.

We don't actually need to fix it, as it's a deprecated feature. But, we do need to remove reference to it from elsewhere.

**Comment by miya0001** [comment]
Roger that. +1

**Comment by miya0001** [comment]
🍻  #2759

**Pull request closed without merging**
