### PR TITLE
Script to create the Git pre-commit hook.

### PR DESCRIPTION
**Pull request by tiagohillebrandt**
Creates a Git pre-commit file to run phpcs once every commit (https://github.com/wp-cli/wp-cli/issues/4474).

### CODE REVIEW

**Comment by gitlost** [comment]
Thanks for the PR @tiagohillebrandt! Although marked for the 1.5.0 milestone, this issue isn't a priority at the moment so it may take a little while before your PR is reviewed.

**Comment by schlessera** [comment]
The immediate problem I see is that this always runs PHPCS over the entire codebase, not over the commit that was staged.

It would be preferable to only check the files or even only lines that are being modified, otherwise you might not be able to commit something due to unrelated problems.

**Comment by danielbachhuber** [comment]
> The immediate problem I see is that this always runs PHPCS over the entire codebase, not over the commit that was staged.

Isn't this what our existing code does? I don't think it's an optimization we need right now...

**Comment by schlessera** [comment]
Yes, you're right. Let's just go with this and try how it plays out. There's nothing preventing us from changing it down the line in case it is problematic.

**Comment by schlessera** [comment]
Hmm, already regretting to have merged this will full check:

image 2018-02-19 at 8 54 57 pm

Takes 25.5 seconds on my system to produce an empty commit.

**Comment by danielbachhuber** [comment]
> Takes 25.5 seconds on my system to produce an empty commit.

Isn't this better than waiting for Travis to build, and then having to come back ground to it?

**Comment by schlessera** [comment]
It just takes too much time. I'll add another PR to change this so it only checks files that were changed.

**Comment by gitlost** [comment]
> Isn't this better than waiting for Travis to build, and then having to come back ground to it?

No!

**Pull request merged**
