### PR TITLE
With the new VERSION file version string detection is only possible

### PR DESCRIPTION
**Pull request by szepeviktor**
... by running wp-cli

### CODE REVIEW

**Comment by szepeviktor** [comment]
Up to 0.19.0 it was possible to grep for `"define.*WP_CLI_VERSION.*;"`.
Now the very end of the phar contains the version string without any fixed string around it.

**Comment by szepeviktor** [comment]
This method is not stable: `tail -n 1 wp-cli.phar| grep -ao "^[0-9.]\+"`

**Comment by danielbachhuber** [comment]
> This method is not stable:

Why not just read the version file?

**Comment by szepeviktor** [comment]
This is implemented: `WPCLI_VER="$(usr/bin/wp cli version|cut -d" " -f2)"`
We are dealing with a phar, there are no files locally.
Could you merge it?

**Comment by danielbachhuber** [comment]
> We are dealing with a phar, there are no files locally.

Oh, right. I forgot the script downloads from Github.

**Pull request merged**
