### PR TITLE
Support custom folder structures in `wp-config.php` file

### PR DESCRIPTION
**Pull request by schlessera**
Adds a regression test for https://github.com/wp-cli/extension-command/issues/247

### CODE REVIEW

**Comment by schlessera** [comment]
As I can't replicate the issue with local tests, I'll merge it to see if the test results are different for more official Phars.

**Comment by janw-me** [comment]
@schlessera  I pulled & switched to this branch.
 And ran `composer behat -- features/wp-config.feature`

And get 2 errors, I guess unrelated to the problem this should address.

```
.F------..F----

(::) failed steps (::)

01. Notice: Undefined index: DB_USER in /home/vagrant/wp-cli-dev/wp-cli-tests/features/bootstrap/FeatureContext.php line 559
    In step `And a wp-config-override.php file:'.                                                    # /home/vagrant/wp-cli-dev/wp-cli-tests/features/steps/given.php:48
    From scenario `Default WordPress install with WP_CONFIG_PATH specified in environment variable'. # features/wp-config.feature:3
    Of feature `wp-config'.                                                                          # features/wp-config.feature

02. Notice: Undefined index: DB_USER in /home/vagrant/wp-cli-dev/wp-cli-tests/features/bootstrap/FeatureContext.php line 559
    In step `And a wp-config.php file:'.                                                             # /home/vagrant/wp-cli-dev/wp-cli-tests/features/steps/given.php:48
    From scenario `__FILE__ and __DIR__ in wp-config.php don't point into the PHAR filesystem'.      # features/wp-config.feature:42
    Of feature `wp-config'.  
```

I'm followed the [handbook](https://make.wordpress.org/cli/handbook/contributions/pull-requests/#functional-tests).
And created the DB & user, I'm running it inside VVV
Am I missing something?

**Comment by schlessera** [comment]
You might need to run `composer install` or even `composer update` after switching to the branch, it requires an updated `wp-cli/wp-cli-tests`.

**Comment by schlessera** [comment]
Regression test was moved over to https://github.com/wp-cli/wp-cli-bundle/pull/309

**Pull request closed without merging**
