### PR TITLE
Update Composer dependencies (2017-06-19)

### PR DESCRIPTION
**Pull request by wp-make-coffee**
```
Loading composer repositories with package information
Updating dependencies
Package operations: 0 installs, 2 updates, 0 removals
  - Updating seld/jsonlint (1.6.0 => 1.6.1):  Checking out 50d63f2858
  - Updating wp-cli/media-command (v1.0.2 => v1.0.3):  Checking out dfa3b80a8d
Writing lock file
Generating autoload files
```

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera Any ideas why this build is failing?

**Comment by schlessera** [comment]
Not yet, it seems to run just fine on my system, though I have PHP 7.0.19, not PHP 7.0.20. Trying to upgrade now to recheck with the same version as Travis...

**Comment by schlessera** [comment]
Hmm, brew's latest stable is still PHP 7.0.19...

**Comment by danielbachhuber** [comment]
@schlessera Clearing all caches and re-running the build seems to have done the trick.

**Comment by schlessera** [comment]
Probably OPcache related then...

**Pull request merged**
