### PR TITLE
GH#4306 Corrected spelling

### PR DESCRIPTION
**Pull request by Sidsector9**
Corrected "Aplies" to "Applies"

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@Sidsector9 As a heads up, you don't need to create a new issue for small changes like these (that you're submitting a pull request for immediately).

**Comment by Sidsector9** [comment]
@danielbachhuber What would be the correct way to fix minor issues like these?

**Comment by danielbachhuber** [comment]
@Sidsector9 Simply open a pull request with the change.

**Comment by Sidsector9** [comment]
@danielbachhuber Cool, will follow it next time.

**Pull request merged**
