### PR TITLE
Fix: Limit ranges of PHP versions

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] limits the ranges of PHP versions this project can be installed with

💁‍♂️ We don't know yet whether this project will work with PHP 9000.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@localheinz Do these pull requests correlate with an existing issue? If not, can you open one first please?

**Comment by localheinz** [comment]
@danielbachhuber 

No, they do not. 

Is it necessary to open an issue for each pull request?

**Comment by danielbachhuber** [comment]
> Is it necessary to open an issue for each pull request?

For this particular pull request, no. For those like https://github.com/wp-cli/scaffold-command/pull/211, it's generally preferred. 

Here's the overview to our contributing process: https://make.wordpress.org/cli/handbook/#contributing

**Comment by localheinz** [comment]
@danielbachhuber 

I took a look at https://make.wordpress.org/cli/handbook/pull-requests/:

> 1. [Search existing issues](https://github.com/issues?utf8=✓&q=is%3Aopen+sort%3Aupdated-desc+org%3Awp-cli); if you can’t find anything related to what you want to work on, open a new issue in the appropriate repository so that you can get some initial feedback.
>    1. Opening an issue before submitting a pull request helps us provide architectural and implementation guidance before you spend too much time on the code.

What kind of guidance would be necessary to decide whether PHP 7.3 should be added to the build matrix?

**Comment by danielbachhuber** [comment]
> What kind of guidance would be necessary to decide whether PHP 7.3 should be added to the build matrix?

`.travis.yml` is duplicated across all of the command repos. I believe @schlessera has some scripting for it.

**Comment by schlessera** [comment]
@localheinz Thanks for the PRs. For the other one, let us please move the discussion over to that repo. I added a comment with more details about why a single PR is problematic in that case: https://github.com/wp-cli/scaffold-command/pull/211#issuecomment-483969505

**Comment by localheinz** [comment]
Thank you, @danielbachhuber and schlessera!

Perhaps this is also something that would make sense to apply to all repositories?

**Pull request merged**
